### ISSUE TITLE
Cannot identify due to either `UserID` or `DeviceID` cannot be empty

### ISSUE THREAD

**Issue by 0x656b694d** [amplitude/analytics-go#47]
Cannot identify due to:
```
amplitude_plugin.go:82: Error: Invalid event, EventType and either UserID or DeviceID cannot be empty: 
        &{EventType:$identify EventOptions:{UserID:4a616e2b-262a-4f24-948f-6599b50f1500 DeviceID:4a616e2b-262a-4f24-948f-6599b50f1500...
```
## Expected Behavior

No error.

## Current Behavior

`Identify()` would not create a _valid_ event.

## Possible Solution

#46

## Steps to Reproduce
 

See #46.

**Comment by kevinpagtakhan** [comment]
@0x656b694d thank you for contributing to Amplitude Go SDK. We have reviewed and merged your PR. We'll get a new version published shortly.
